### ISSUE TITLE
Update tests to reflect changes to button copy.

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests#671]
Install buttons now say "Install for free" or Install for <price>".

We need to update the tests to reflect this change.

**Comment by bobsilverberg** [comment]
I am working on this.

**Comment by m8ttyB** [comment]
@bobsilverberg are you still working on this?

**Comment by bobsilverberg** [comment]
@m8ttyB I submitted a couple of PRs that address this, which have been merged. I think all has been addressed, but we should make one last look at any outstanding failures to be sure they are not related to this change. If there are not any then this issue can be closed.

**Comment by rbillings** [comment]
Verified recent failures are not related to the install button, closing.

**Comment by rbillings** [comment]
I take it back, this is still happening: https://webqa-ci.mozilla.com/job/amo.stage.saucelabs/

**Comment by rbillings** [comment]
Sorry sorry [getting my buildmaster legs], the failure is from https://github.com/mozilla/Addon-Tests/issues/773, not the button copy.
